/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.view;

import app.controller.MahasiswaController;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import app.model.Mahasiswa;
import java.awt.print.*;
import java.text.MessageFormat;
import javax.swing.*;
/**
 *
 * @author Satria Yuda
 */
public class MahasiswaView extends javax.swing.JFrame {
private MahasiswaController mahasiswaController = new MahasiswaController();
    /**
     * Creates new form Mahasiswa
     */
    public MahasiswaView(String akses) {
        initComponents();
        if(akses == null){
            JOptionPane.showMessageDialog(null, "Login Terlebih Dahulu");
            System.exit(0);
        }
    loadTableData();
    }
    private void loadTableData() {
    List<Mahasiswa> mahasiswaList = mahasiswaController.getAllMahasiswa();
    DefaultTableModel model = (DefaultTableModel) tbl_mahasiswa.getModel();
    model.setRowCount(0); // Clear existing data
    
    for (Mahasiswa mahasiswa : mahasiswaList) {
        model.addRow(new Object[]{mahasiswa.getNim(), mahasiswa.getNama(), mahasiswa.getKelas(), mahasiswa.getProdi(),mahasiswa.getTingkat(),mahasiswa.getPassword()});
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_nama = new javax.swing.JTextField();
        txt_nim = new javax.swing.JTextField();
        btn_edit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txt_kelas = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btn_hapus = new javax.swing.JButton();
        btn_tambah = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_mahasiswa = new javax.swing.JTable();
        cmb_prodi = new javax.swing.JComboBox<>();
        btn_logout = new javax.swing.JButton();
        btn_absensi = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_password = new javax.swing.JTextField();
        cmb_tingkat = new javax.swing.JComboBox<>();
        bg = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Data Mahasiswa");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 200, 50));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("NIM");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 40, 20));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Nama");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        txt_nama.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(txt_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 230, -1));

        txt_nim.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(txt_nim, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 230, -1));

        btn_edit.setBackground(new java.awt.Color(0, 0, 204));
        btn_edit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_edit.setForeground(new java.awt.Color(255, 255, 255));
        btn_edit.setText("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });
        jPanel1.add(btn_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 80, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Kelas");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        txt_kelas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(txt_kelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 230, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Prodi");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        btn_hapus.setBackground(new java.awt.Color(0, 0, 204));
        btn_hapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_hapus.setForeground(new java.awt.Color(255, 255, 255));
        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });
        jPanel1.add(btn_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 80, 30));

        btn_tambah.setBackground(new java.awt.Color(0, 0, 204));
        btn_tambah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_tambah.setForeground(new java.awt.Color(255, 255, 255));
        btn_tambah.setText("Tambah");
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });
        jPanel1.add(btn_tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 80, 30));

        tbl_mahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "NIM", "Nama", "Kelas", "Prodi", "Tingkat", "Password"
            }
        ));
        tbl_mahasiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_mahasiswaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_mahasiswa);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 380, 350));

        cmb_prodi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmb_prodi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "D-III Statistika", "D-IV Statistika", "D-IV Komputasi Statistik" }));
        jPanel1.add(cmb_prodi, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 230, -1));

        btn_logout.setBackground(new java.awt.Color(0, 0, 204));
        btn_logout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_logout.setForeground(new java.awt.Color(255, 255, 255));
        btn_logout.setText("Logout");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        jPanel1.add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 440, 80, 30));

        btn_absensi.setBackground(new java.awt.Color(102, 204, 255));
        btn_absensi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_absensi.setForeground(new java.awt.Color(255, 255, 255));
        btn_absensi.setText("Daftar Presensi Mahasiswa");
        btn_absensi.setBorder(null);
        btn_absensi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_absensiActionPerformed(evt);
            }
        });
        jPanel1.add(btn_absensi, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 210, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Tingkat");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Password");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        txt_password.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 230, -1));

        cmb_tingkat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmb_tingkat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2" }));
        jPanel1.add(cmb_tingkat, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 230, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bg.jpg"))); // NOI18N
        bg.setText("jLabel1");
        bg.setPreferredSize(new java.awt.Dimension(626, 438));
        jPanel1.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 490));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        if(txt_nim.getText().equals("") || txt_nama.getText().equals("") || txt_kelas.getText().equals("") || txt_password.getText().equals("") || cmb_prodi.getSelectedItem().equals("") || cmb_tingkat.getSelectedItem().equals("")){
            JOptionPane.showMessageDialog(this, "Lengkapi data terlebih dahulu!");
        }else{
        Mahasiswa mahasiswa = new Mahasiswa(
            txt_nim.getText(),
            txt_nama.getText(),
            txt_kelas.getText(),
            cmb_prodi.getSelectedItem().toString(),
            cmb_tingkat.getSelectedItem().toString(),
            txt_password.getText()
    );
    mahasiswaController.tambahMahasiswa(mahasiswa);
    loadTableData();
        }
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        if(txt_nim.getText().equals("") || txt_nama.getText().equals("") || txt_kelas.getText().equals("") || txt_password.getText().equals("") || cmb_prodi.getSelectedItem().equals("") || cmb_tingkat.getSelectedItem().equals("")){
            JOptionPane.showMessageDialog(this, "Pilih data terlebih dahulu!");
        }else{
            Mahasiswa mahasiswa = new Mahasiswa(
            txt_nim.getText(),
            txt_nama.getText(),
            txt_kelas.getText(),
            cmb_prodi.getSelectedItem().toString(),
            cmb_tingkat.getSelectedItem().toString(),
                txt_password.getText()
    );
    mahasiswaController.editMahasiswa(mahasiswa);
    loadTableData();
        }
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        String nim = txt_nim.getText();
        if(nim.equals("")){
            JOptionPane.showMessageDialog(this, "Pilih data terlebih dahulu!");
        }else{
            mahasiswaController.hapusMahasiswa(nim);
            loadTableData();
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void tbl_mahasiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_mahasiswaMouseClicked
        int selectedRow = tbl_mahasiswa.getSelectedRow();
    DefaultTableModel model = (DefaultTableModel) tbl_mahasiswa.getModel();
    
    // Mendapatkan nilai dari tabel berdasarkan baris yang diklik
    String nim = model.getValueAt(selectedRow, 0).toString();
    String nama = model.getValueAt(selectedRow, 1).toString();
    String kelas = model.getValueAt(selectedRow, 2).toString();
    String prodi = model.getValueAt(selectedRow, 3).toString();
    String tingkat = model.getValueAt(selectedRow, 4).toString();
    String password = model.getValueAt(selectedRow, 5).toString();
    
    // Menampilkan nilai di input field
    txt_nim.setText(nim);
    txt_nama.setText(nama);
    txt_kelas.setText(kelas);
    cmb_prodi.setSelectedItem(prodi);
    cmb_tingkat.setSelectedItem(tingkat);
    txt_password.setText(password);
    }//GEN-LAST:event_tbl_mahasiswaMouseClicked

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_absensiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_absensiActionPerformed
        new PresensiView("0", "0", "0", "1").setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_absensiActionPerformed
    private void printTable(JTable table, String title) {
    try {
        boolean complete = table.print(JTable.PrintMode.FIT_WIDTH, new MessageFormat(title), null);
        if (complete) {
            JOptionPane.showMessageDialog(null, "Printing Complete", "Printing Result", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Printing Cancelled", "Printing Result", JOptionPane.INFORMATION_MESSAGE);
        }
    } catch (PrinterException pe) {
        JOptionPane.showMessageDialog(null, "Printing Failed: " + pe.getMessage(), "Printing Result", JOptionPane.ERROR_MESSAGE);
    }
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MahasiswaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MahasiswaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MahasiswaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MahasiswaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MahasiswaView(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton btn_absensi;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JComboBox<String> cmb_prodi;
    private javax.swing.JComboBox<String> cmb_tingkat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tbl_mahasiswa;
    private javax.swing.JTextField txt_kelas;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_nim;
    private javax.swing.JTextField txt_password;
    // End of variables declaration//GEN-END:variables
}
